name: genderme
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  record: ^5.0.5
  sqflite: ^2.3.3+1
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/
